name: Build Obfuscate BPB Panel

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 1 * * *" # Daily at 1:00 AM

permissions:
  contents: write

jobs:
  book:
    runs-on: ubuntu-latest
    timeout-minutes: 10 # Fail fast if it takes too long
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm # Cache npm dependencies
      - run: npm install -g javascript-obfuscator
      - run: curl -L -o origin.js https://raw.githubusercontent.com/bia-pain-bache/BPB-Worker-Panel/main/build/unobfuscated-worker.js
      - run: |
          javascript-obfuscator origin.js --output _worker.js \
            --compact true \
            --control-flow-flattening false \
            --dead-code-injection false \
            --identifier-names-generator hexadecimal \
            --string-array true \
            --string-array-encoding base64 \
            --string-array-threshold 0.75 \
            --transform-object-keys false
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: ':arrow_up: update latest bpb panel'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
